"""Write PROJECTS.md from the snapshot, so the index cannot drift from the
account. Descriptions are GitHub's own; the grouping is the one editorial
choice, and it lives in themes.py.
"""
from __future__ import annotations

from datetime import datetime

from common import ROOT, full_name, projects, repos
from themes import AREAS, LEARNING, THEME

GH = "https://github.com"
OWNER = "adarshcod30"


def main() -> None:
    ps = projects()
    ds = sorted(datetime.fromisoformat(r["createdAt"].replace("Z", "+00:00"))
                for r in ps)
    cadence = round((ds[-1] - ds[0]).days / max(1, len(ds) - 1))

    L: list[str] = []
    a = L.append
    a("# Every project, grouped")
    a("")
    a(f"{len(ps)} substantive projects, one every {cadence} days on average. "
      "This page is generated from the GitHub API by `make index`, so it "
      "cannot fall behind the account.")
    a("")
    a("[Back to the profile](README.md)")
    a("")

    for area, _colour, blurb in AREAS:
        members = [r for r in ps if THEME[r["name"]][0] == area]
        if not members:
            continue
        members.sort(key=lambda r: (-THEME[r["name"]][1], r["name"].lower()))
        a(f"## {area}")
        a("")
        a(f"*{blurb}*")
        a("")
        a("| Project | Built with | What it does |")
        a("|---|---|---|")
        for r in members:
            langs = ", ".join(e["node"]["name"]
                              for e in r["languages"]["edges"][:3]) or "-"
            desc = (r.get("description") or "").replace("|", "\\|").strip()
            # an organisation repository lives under the organisation, not me
            label = r["name"] + (f" ⟨{r['org']}⟩" if r.get("org") else "")
            a(f"| **[{label}]({GH}/{full_name(r)})** | {langs} | {desc} |")
        a("")

    learn = [r for r in repos() if r["name"] in LEARNING]
    if learn:
        a("## Where I started")
        a("")
        a("Kept public on purpose. The first commits are not good, and that is "
          "the point of leaving them up.")
        a("")
        a("| Repository | Started |")
        a("|---|---|")
        for r in sorted(learn, key=lambda r: r["createdAt"]):
            a(f"| [{r['name']}]({GH}/{OWNER}/{r['name']}) | {r['createdAt'][:10]} |")
        a("")

    a("---")
    a("")
    a("Generated by `make index`.")
    a("")

    out = ROOT / "PROJECTS.md"
    out.write_text("\n".join(L))
    print("wrote", out)


if __name__ == "__main__":
    main()
